"""
Standard Institutional Portfolio Presets and Candidate Universe for CFTC Rule 1.25.
"""

from decimal import Decimal
from datetime import date, timedelta
from typing import List, Dict
from .types import AssetClass, CreditRating, LiquidityTier, YieldType, to_decimal, round_money
from .instruments import Instrument, Position
from .portfolio import TreasuryPortfolio

def get_standard_universe(as_of_date: date) -> List[Instrument]:
    """Returns comprehensive universe of CFTC Rule 1.25 permitted instruments across all statutory categories."""
    return [
        # --- 1. Segregated Depository Cash Accounts (17 CFR § 1.20 / § 1.49) ---
        Instrument(
            id="CASH-FED-RESERVE",
            name="Federal Reserve Bank Segregated Cash Deposit",
            asset_class=AssetClass.CASH_CENTRAL_BANK,
            issuer="FEDERAL_RESERVE",
            issuer_family="FEDERAL_RESERVE",
            maturity_date=None,
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (U.S. Central Bank Reserve Balance § 1.20)",
            liquidity_tier=LiquidityTier.TIER_0_INSTANT,
            settlement_terms="Immediate Fedwire Real-Time Gross Settlement (RTGS Intraday Availability)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0380"),
            yield_type=YieldType.FED_IORB,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            cusip=None,
            internal_id="FED-MA-102948-NY",
            depository_account_type="17 CFR § 1.20 Federal Reserve Master Account",
            rule_125_status="Segregated Depository Cash (§ 1.20 / Central Bank)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Federal Reserve Operating Circular 1 & 4 on file)",
            embedded_derivative_check="Passed (Pure central bank reserve deposit; no derivatives)",
        ),
        Instrument(
            id="CASH-BNY-CUSTODY",
            name="BNY Mellon Segregated Custody Account (Cash)",
            asset_class=AssetClass.CASH_CENTRAL_BANK,
            issuer="BNY_MELLON",
            issuer_family="BNY_MELLON",
            maturity_date=None,
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AA_MINUS,
            credit_rating_informational="AA- (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (G-SIB Qualifying Commercial Custodian § 1.49)",
            liquidity_tier=LiquidityTier.TIER_0_INSTANT,
            settlement_terms="Same-Day Fedwire / CHIPS Wire (Cutoff 17:00 ET)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0370"),
            yield_type=YieldType.CONTRACT_CUSTODY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            cusip=None,
            internal_id="BNY-CUST-883920-SEG",
            depository_account_type="17 CFR § 1.20 / § 1.49 Segregated Commercial Custody Account",
            rule_125_status="Segregated Depository Cash (§ 1.20 / Commercial Bank)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Custodial Agreement & Letter of Acknowledgment on file)",
            embedded_derivative_check="Passed (Pure commercial bank demand deposit; no derivatives)",
        ),

        # --- 2. Direct U.S. Government Obligations — Treasury Bills (17 CFR § 1.25(a)(1)(i)) ---
        Instrument(
            id="UST-TBILL-4W",
            name="4-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2026, 9, 22),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03701"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("99.73"),
            bid_ask_spread_bps=Decimal("0.8"),
            cusip="912797VD6",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-TBILL-8W",
            name="8-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2026, 10, 20),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03727"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("99.44"),
            bid_ask_spread_bps=Decimal("0.8"),
            cusip="912797VM6",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-TBILL-13W",
            name="13-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2026, 11, 19),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03802"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("99.11"),
            bid_ask_spread_bps=Decimal("0.9"),
            cusip="912797UZ8",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-TBILL-17W",
            name="17-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2026, 12, 22),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03850"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("98.75"),
            bid_ask_spread_bps=Decimal("0.9"),
            cusip="912797WG8",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-TBILL-26W",
            name="26-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2027, 2, 18),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03907"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("98.10"),
            bid_ask_spread_bps=Decimal("1.0"),
            cusip="912797TV9",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-TBILL-52W",
            name="52-Week Treasury Bill",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2027, 8, 5),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire (Discount Window Eligible)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.04054"),
            yield_type=YieldType.AUCTION_INVESTMENT_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("96.14"),
            bid_ask_spread_bps=Decimal("1.0"),
            cusip="912797VR5",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct U.S. Government Obligation; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Auction Announcement on file)",
            embedded_derivative_check="Passed (Plain vanilla zero-coupon bill; no embedded options § 1.25(b)(2)(ii))",
        ),

        # --- 3. Direct U.S. Government Obligations — Floating Rate Notes (17 CFR § 1.25(a)(1)(i) & § 1.25(b)(2)(i)(C)) ---
        Instrument(
            id="UST-FRN-2Y",
            name="2-Year Treasury Floating Rate Note",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2028, 7, 31),
            coupon_rate=Decimal("0.03852"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.03852"),
            yield_type=YieldType.INDEX_EFFECTIVE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("1.2"),
            is_floating=True,
            reset_frequency_days=7,
            cusip="91282CRD5",
            rule_125_status="Eligible (§ 1.25(b)(2)(i)(C) Permitted Treasury Floating Rate Note; 100% No Limit)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect FRN Offering Circular on file)",
            embedded_derivative_check="Passed (Indexed to 13-week T-Bill auction rate; permitted under § 1.25(b)(2)(i)(C))",
        ),

        # --- 4. Direct U.S. Government Obligations — Fixed Rate Treasury Notes (17 CFR § 1.25(a)(1)(i)) ---
        Instrument(
            id="UST-NOTE-2Y",
            name="2-Year Treasury Note 4.250%",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2028, 7, 31),
            coupon_rate=Decimal("0.0425"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0425"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("1.2"),
            cusip="91282CRB9",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct Fixed-Rate Treasury Note; WAM <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Note Circular on file)",
            embedded_derivative_check="Passed (Plain vanilla semi-annual fixed coupon; no options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-NOTE-3Y",
            name="3-Year Treasury Note 4.250%",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2029, 8, 15),
            coupon_rate=Decimal("0.0425"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0425"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("1.4"),
            cusip="91282CRG8",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct Fixed-Rate Treasury Note; WAM <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Note Circular on file)",
            embedded_derivative_check="Passed (Plain vanilla semi-annual fixed coupon; no options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="UST-NOTE-5Y",
            name="5-Year Treasury Note 4.375%",
            asset_class=AssetClass.US_TREASURY,
            issuer="US_TREASURY",
            issuer_family="US_TREASURY",
            maturity_date=date(2031, 7, 31),
            coupon_rate=Decimal("0.04375"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit of the U.S. Government)",
            liquidity_tier=LiquidityTier.TIER_1_SAME_DAY,
            settlement_terms="T+1 Secondary Market DVP / Fedwire",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.04375"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("1.5"),
            cusip="91282CRA1",
            rule_125_status="Eligible (§ 1.25(a)(1)(i) Direct Fixed-Rate Treasury Note; WAM <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (TreasuryDirect Note Circular on file)",
            embedded_derivative_check="Passed (Plain vanilla semi-annual fixed coupon; no options § 1.25(b)(2)(ii))",
        ),

        # --- 5. Repurchase Agreements (17 CFR § 1.25(a)(2) & § 1.25(d)) ---
        Instrument(
            id="REPO-ON-SOFR",
            name="Overnight Reverse Repo (FICC Central Counterparty Clearing DVP)",
            asset_class=AssetClass.REVERSE_REPO,
            issuer="FICC_DVP",
            issuer_family="DTCC",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Centrally Cleared via FICC GSD Netting / CCP Guarantee)",
            liquidity_tier=LiquidityTier.TIER_0_INSTANT,
            settlement_terms="Overnight Demand / Cash Return at 08:30 ET via FICC DVP Fedwire",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0380"),
            yield_type=YieldType.REPO_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            cusip=None,
            internal_id="FICC-DVP-20260827-01",
            master_agreement_ref="FICC Government Securities Division Rules (102% Collateral: UST-912797UZ8)",
            rule_125_status="Eligible (§ 1.25(a)(2) / § 1.25(d) Centrally Cleared Repo; Collateral Limits Apply)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (FICC GSD Membership & Netting Agreement on file)",
            embedded_derivative_check="Passed (Standard 1-day repo; no derivatives or options)",
        ),
        Instrument(
            id="REPO-BILAT-UST",
            name="Overnight Bilateral Treasury Reverse Repo (JPMorgan Chase Primary Dealer)",
            asset_class=AssetClass.REVERSE_REPO,
            issuer="JPMORGAN",
            issuer_family="JPMORGAN",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Primary Dealer Counterparty / 102% Daily MTM Margin)",
            liquidity_tier=LiquidityTier.TIER_0_INSTANT,
            settlement_terms="Overnight Demand / Bilateral Fedwire Return at 08:30 ET",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0382"),
            yield_type=YieldType.REPO_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            cusip=None,
            internal_id="JPM-BILAT-20260827-04",
            master_agreement_ref="SIFMA Master Repurchase Agreement dated 01/15/2024 (102% Collateral: UST-91282CRB9)",
            rule_125_status="Eligible (§ 1.25(a)(2) / § 1.25(d)(2) Bilateral Repo; 25% Counterparty Group Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Executed SIFMA MRA & Custody Letter of Acknowledgment on file)",
            embedded_derivative_check="Passed (Standard 1-day bilateral repo; no derivatives or options)",
        ),
        Instrument(
            id="REPO-AGENCY-ON",
            name="Overnight Tri-Party Agency GSE Reverse Repo (BNY Mellon Tri-Party)",
            asset_class=AssetClass.REVERSE_REPO,
            issuer="BNY_MELLON",
            issuer_family="BNY_MELLON",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Tri-Party Custodial Guarantee / 102% Collateral Margin)",
            liquidity_tier=LiquidityTier.TIER_0_INSTANT,
            settlement_terms="Overnight Tri-Party Custodial Liquidity Settlement (BNY Mellon System)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0383"),
            yield_type=YieldType.REPO_RATE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            cusip=None,
            internal_id="BNY-TRIPARTY-20260827-09",
            master_agreement_ref="BNY Mellon Tri-Party Custodial Repo Agreement (102% Collateral: FNMA-3135G0Q22)",
            rule_125_status="Eligible (§ 1.25(a)(2) / § 1.25(d)(2) Tri-Party Repo; 25% Counterparty Group Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Tri-Party Custodial Agreement on file)",
            embedded_derivative_check="Passed (Standard 1-day tri-party repo; no derivatives or options)",
        ),

        # --- 6. Rule 2a-7 Government Money Market Mutual Funds (17 CFR § 1.25(a)(1)(vii)) ---
        Instrument(
            id="MMMF-BLK-TREASURY",
            name="BlackRock Treasury Trust Fund Institutional (TTTXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="BLACKROCK",
            issuer_family="BLACKROCK",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0378"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("45000000000.00"),
            cusip="09248U551",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Treasury backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-BLK-FEDFUND",
            name="BlackRock FedFund Institutional (TFDXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="BLACKROCK",
            issuer_family="BLACKROCK",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0380"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("60000000000.00"),
            cusip="09248U700",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% Govt/Fed Repo backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-JPM-CAPITAL",
            name="JPMorgan U.S. Government MMF—Capital (OGVXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="JPMORGAN",
            issuer_family="JPMORGAN",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0376"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("75000000000.00"),
            cusip="4812C0670",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-JPM-INST",
            name="JPMorgan U.S. Government MMF—Institutional (IJGXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="JPMORGAN",
            issuer_family="JPMORGAN",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0382"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("50000000000.00"),
            cusip="4812C2684",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-FID-GOVT",
            name="Fidelity Investments MM Government Portfolio (FGGXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="FIDELITY",
            issuer_family="FIDELITY",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0379"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("40000000000.00"),
            cusip="316175108",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-GS-FSGOVT",
            name="GS Financial Square Government Fund Institutional (FGTXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="GOLDMAN_SACHS",
            issuer_family="GOLDMAN_SACHS",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0381"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("35000000000.00"),
            cusip="38141W273",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-VANG-FED",
            name="Vanguard Federal Money Market Fund (VMFXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="VANGUARD",
            issuer_family="VANGUARD",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0383"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("80000000000.00"),
            cusip="922906300",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),
        Instrument(
            id="MMMF-MS-GOVT",
            name="Morgan Stanley Institutional Liquidity Government Securities Portfolio (MVIXX)",
            asset_class=AssetClass.MMMF_GOVT_LARGE,
            issuer="MORGAN_STANLEY",
            issuer_family="MORGAN_STANLEY",
            maturity_date=as_of_date + timedelta(days=1),
            coupon_rate=Decimal("0.00"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA-mf (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (§ 1.25(c) Qualifying 2a-7 Government MMF)",
            liquidity_tier=LiquidityTier.TIER_2_NEXT_DAY,
            settlement_terms="T+1 Next-Day Redemption Wire (Cutoff 15:00 ET; No Discretionary Fees/Gates § 1.25(c)(5)(ii))",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0380"),
            yield_type=YieldType.SEC_7DAY,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("0.0"),
            fund_total_aum=Decimal("30000000000.00"),
            cusip="61747C830",
            rule_125_status="Eligible (§ 1.25(a)(1)(vii) Large Qualifying Govt MMF; 50% Agg / 10% Fund / 25% Family)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (SEC Form N-MFP / Fund Prospectus on file)",
            embedded_derivative_check="Passed (100% US Govt backed; no derivatives § 1.25(c))",
        ),

        # --- 7. U.S. Agency GSE Debt Obligations (17 CFR § 1.25(a)(1)(iii)) ---
        Instrument(
            id="GSE-FNMA-3135G0Q22",
            name="Fannie Mae Benchmark Note 1.875%",
            asset_class=AssetClass.US_AGENCY,
            issuer="FNMA",
            issuer_family="FNMA",
            maturity_date=date(2026, 9, 24),
            coupon_rate=Decimal("0.01875"),
            credit_rating=CreditRating.AA_PLUS,
            credit_rating_informational="AA+ (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (U.S. GSE Senior Unsecured Obligation / Conservatorship)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 Fedwire Securities DVP (High Secondary Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0395"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("99.80"),
            bid_ask_spread_bps=Decimal("2.5"),
            cusip="3135G0Q22",
            rule_125_status="Eligible (§ 1.25(a)(1)(iii) U.S. Agency GSE Obligation; 50% Agg / 25% Single GSE Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Fannie Mae Debt Offering Prospectus on file)",
            embedded_derivative_check="Passed (Plain vanilla bullet debenture; no call/put options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="GSE-FNMA-3135G05Y5",
            name="Fannie Mae Benchmark Note 0.750%",
            asset_class=AssetClass.US_AGENCY,
            issuer="FNMA",
            issuer_family="FNMA",
            maturity_date=date(2027, 10, 8),
            coupon_rate=Decimal("0.0075"),
            credit_rating=CreditRating.AA_PLUS,
            credit_rating_informational="AA+ (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (U.S. GSE Senior Unsecured Obligation / Conservatorship)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 Fedwire Securities DVP (High Secondary Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0405"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("98.70"),
            bid_ask_spread_bps=Decimal("3.0"),
            cusip="3135G05Y5",
            rule_125_status="Eligible (§ 1.25(a)(1)(iii) U.S. Agency GSE Obligation; 50% Agg / 25% Single GSE Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (Fannie Mae Debt Offering Prospectus on file)",
            embedded_derivative_check="Passed (Plain vanilla bullet debenture; no call/put options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="GSE-FHLB-3130B9RC6",
            name="FHLBanks Global Bond 3.500%",
            asset_class=AssetClass.US_AGENCY,
            issuer="FHLB",
            issuer_family="FHLB",
            maturity_date=date(2028, 3, 3),
            coupon_rate=Decimal("0.0350"),
            credit_rating=CreditRating.AA_PLUS,
            credit_rating_informational="AA+ (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Joint & Several Obligation of the 11 FHLBanks)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 Fedwire Securities DVP (High Secondary Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0415"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("98.95"),
            bid_ask_spread_bps=Decimal("2.5"),
            cusip="3130B9RC6",
            rule_125_status="Eligible (§ 1.25(a)(1)(iii) U.S. Agency GSE Obligation; 50% Agg / 25% Single GSE Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (FHLBanks Consolidated Bond Prospectus on file)",
            embedded_derivative_check="Passed (Plain vanilla bullet debenture; no call/put options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="GSE-FFCB-3133EWXT2",
            name="Federal Farm Credit Banks Bond 4.125% Bullet",
            asset_class=AssetClass.US_AGENCY,
            issuer="FFCB",
            issuer_family="FFCB",
            maturity_date=date(2027, 8, 6),
            coupon_rate=Decimal("0.04125"),
            credit_rating=CreditRating.AA_PLUS,
            credit_rating_informational="AA+ (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Joint & Several Obligation of the Farm Credit System)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 Fedwire Securities DVP (High Secondary Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0410"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("99.85"),
            bid_ask_spread_bps=Decimal("2.5"),
            cusip="3133EWXT2",
            rule_125_status="Eligible (§ 1.25(a)(1)(iii) U.S. Agency GSE Obligation; 50% Agg / 25% Single GSE Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (FFCB Consolidated Systemwide Bond Circular on file)",
            embedded_derivative_check="Passed (Plain vanilla bullet debenture; no call/put options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="GSE-FFCB-3133EWZF0",
            name="Federal Farm Credit Banks SOFR Float Note",
            asset_class=AssetClass.US_AGENCY,
            issuer="FFCB",
            issuer_family="FFCB",
            maturity_date=date(2028, 8, 25),
            coupon_rate=Decimal("0.0392"),
            credit_rating=CreditRating.AA_PLUS,
            credit_rating_informational="AA+ (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Joint & Several Obligation of the Farm Credit System)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 Fedwire Securities DVP (High Secondary Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0392"),
            yield_type=YieldType.INDEX_EFFECTIVE,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("2.5"),
            is_floating=True,
            reset_frequency_days=1,
            cusip="3133EWZF0",
            rule_125_status="Eligible (§ 1.25(b)(2)(i)(C) Permitted GSE Floating Rate Note; 50% Agg / 25% Issuer Cap)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (FFCB Floating Rate Note Offering Circular on file)",
            embedded_derivative_check="Passed (Indexed to SOFR + 12 bps; no caps/floors/options § 1.25(b)(2)(ii))",
        ),

        # --- 8. Municipal General Obligations (17 CFR § 1.25(a)(1)(ii)) ---
        Instrument(
            id="MUNI-CA-13063C5D8",
            name="State of California General Obligation Various Purpose",
            asset_class=AssetClass.MUNICIPAL,
            issuer="STATE_OF_CALIFORNIA",
            issuer_family="CALIFORNIA",
            maturity_date=as_of_date + timedelta(days=365),
            coupon_rate=Decimal("0.0400"),
            credit_rating=CreditRating.AA_MINUS,
            credit_rating_informational="AA- (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Ultimate Full Faith & Credit of the State of California)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 DTC / Fedwire Settlement (High Secondary Market Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0365"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("12.0"),
            cusip="13063C5D8",
            rule_125_status="Eligible (§ 1.25(a)(1)(ii) Municipal UTGO Obligation; 10% Agg / 5% Issuer Limit; Tenor <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (State of CA Official Statement on file)",
            embedded_derivative_check="Passed (Plain vanilla fixed-rate UTGO; no derivatives/options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="MUNI-NYC-64966Q",
            name="City of New York General Obligation Bonds",
            asset_class=AssetClass.MUNICIPAL,
            issuer="CITY_OF_NEW_YORK",
            issuer_family="NEW_YORK",
            maturity_date=as_of_date + timedelta(days=365),
            coupon_rate=Decimal("0.0400"),
            credit_rating=CreditRating.AA,
            credit_rating_informational="AA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Full Faith & Credit Unlimited Tax GO of City of New York)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 DTC / Fedwire Settlement (High Secondary Market Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0370"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("12.0"),
            cusip="64966QXX1",
            rule_125_status="Eligible (§ 1.25(a)(1)(ii) Municipal UTGO Obligation; 10% Agg / 5% Issuer Limit; Tenor <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (City of New York Official Statement on file)",
            embedded_derivative_check="Passed (Plain vanilla fixed-rate UTGO; no derivatives/options § 1.25(b)(2)(ii))",
        ),
        Instrument(
            id="MUNI-TX-882723",
            name="State of Texas Veterans General Obligation Bond",
            asset_class=AssetClass.MUNICIPAL,
            issuer="STATE_OF_TEXAS",
            issuer_family="TEXAS",
            maturity_date=as_of_date + timedelta(days=730),
            coupon_rate=Decimal("0.0400"),
            credit_rating=CreditRating.AAA,
            credit_rating_informational="AAA (Informational Only)",
            credit_risk_assessment="Minimal Credit Risk (Constitutional General Obligation of the State of Texas)",
            liquidity_tier=LiquidityTier.TIER_3_TERM,
            settlement_terms="T+1 DTC / Fedwire Settlement (High Secondary Market Liquidity)",
            cash_conversion_within_1_biz_day=True,
            yield_to_maturity=Decimal("0.0360"),
            yield_type=YieldType.YTM,
            yield_as_of="2026-08-27 16:00 EDT",
            clean_price=Decimal("100.00"),
            bid_ask_spread_bps=Decimal("14.0"),
            cusip="882723XX1",
            rule_125_status="Eligible (§ 1.25(a)(1)(ii) Municipal UTGO Obligation; 10% Agg / 5% Issuer Limit; Tenor <= 2Y)",
            liquidity_evidence_date=date(2026, 8, 27),
            offering_doc_reviewed="Passed (State of Texas Official Statement on file)",
            embedded_derivative_check="Passed (Plain vanilla fixed-rate UTGO; no derivatives/options § 1.25(b)(2)(ii))",
        ),
    ]

class PortfolioPresets:
    """
    Standard portfolio configurations for demonstrations and stress benchmarking.
    """

    @staticmethod
    def get_balanced_institutional_fcm(as_of_date: date, total_float: Decimal = Decimal("500000000.00")) -> TreasuryPortfolio:
        """
        $500M Institutional Prime FCM Treasury Portfolio.
        Fully compliant with CFTC 1.25, balanced yield (5.18%), WAM 0.45 yrs, robust T+0 liquidity.
        """
        insts = {inst.id: inst for inst in get_standard_universe(as_of_date)}
        firm_ri = round_money(total_float * Decimal("0.05")) # 5% RI cushion

        def make_pos(inst_id: str, pct: Decimal) -> Position:
            inst = insts[inst_id]
            alloc_usd = round_money(total_float * pct)
            par = round_money(alloc_usd / (inst.clean_price / Decimal("100.0")))
            return Position(instrument=inst, par_amount=par, book_cost=alloc_usd)

        positions = [
            make_pos("UST-TBILL-13W", Decimal("0.25")),      # 25% 13W T-Bills
            make_pos("UST-TBILL-26W", Decimal("0.15")),      # 15% 26W T-Bills
            make_pos("UST-NOTE-2Y", Decimal("0.10")),        # 10% 2Y T-Notes
            make_pos("REPO-ON-SOFR", Decimal("0.15")),       # 15% Overnight SOFR Reverse Repo
            make_pos("MMMF-BLK-TREASURY", Decimal("0.08")),  # 8% BlackRock Treasury Trust MMMF (<= 10% family cap)
            make_pos("MMMF-JPM-INST", Decimal("0.08")),      # 8% JPMorgan Govt MMMF (<= 10% family cap)
            make_pos("GSE-FNMA-3135G0Q22", Decimal("0.07")),# 7% FNMA Benchmark Note
            make_pos("GSE-FFCB-3133EWXT2", Decimal("0.03")),# 3% Farm Credit Bullet Bond
        ]

        # Total positions sum = 25+15+10+15+8+8+7+3 = 91%
        # Cash at Fed = 9% of customer float + 5% firm RI = 14%
        cash_at_fed = round_money(total_float * Decimal("0.09")) + firm_ri

        return TreasuryPortfolio(
            as_of_date=as_of_date,
            customer_segregated_liability=total_float,
            firm_residual_interest=firm_ri,
            cash_at_fed=cash_at_fed,
            positions=positions
        )

    @staticmethod
    def get_aggressive_yield_chaser(as_of_date: date, total_float: Decimal = Decimal("500000000.00")) -> TreasuryPortfolio:
        """
        Aggressive Yield Chaser: Pushes right up against 1.25 regulatory limits.
        40% MMMF (near 50% cap), 30% Agency GSEs (near 50% cap), 5% Muni (5% issuer cap).
        High yield, but high vulnerability to T+1 DCO margin call liquidity shocks.
        """
        insts = {inst.id: inst for inst in get_standard_universe(as_of_date)}
        firm_ri = round_money(total_float * Decimal("0.03")) # 3% RI

        def make_pos(inst_id: str, pct: Decimal) -> Position:
            inst = insts[inst_id]
            alloc_usd = round_money(total_float * pct)
            par = round_money(alloc_usd / (inst.clean_price / Decimal("100.0")))
            return Position(instrument=inst, par_amount=par, book_cost=alloc_usd)

        positions = [
            make_pos("MMMF-BLK-TREASURY", Decimal("0.10")), # 10% (at 10% family cap)
            make_pos("MMMF-JPM-INST", Decimal("0.10")),     # 10%
            make_pos("MMMF-FID-GOVT", Decimal("0.10")),     # 10%
            make_pos("MMMF-GS-FSGOVT", Decimal("0.10")),    # 10% (Total MMMF 40% <= 50% cap)
            make_pos("GSE-FNMA-3135G0Q22", Decimal("0.15")),# 15% Fannie Mae (<= 25% single GSE)
            make_pos("GSE-FHLB-3130B9RC6", Decimal("0.15")),# 15% FHLB (Total Agency 30% <= 50% cap)
            make_pos("MUNI-CA-13063C5D8", Decimal("0.05")), # 5% (at 5% single issuer cap)
            make_pos("UST-NOTE-2Y", Decimal("0.24")),       # 24% 2Y Notes
        ]

        # Total positions sum = 40 + 30 + 5 + 24 = 99%
        # Cash at Fed = 1% + firm_ri
        cash_at_fed = round_money(total_float * Decimal("0.01")) + firm_ri

        return TreasuryPortfolio(
            as_of_date=as_of_date,
            customer_segregated_liability=total_float,
            firm_residual_interest=firm_ri,
            cash_at_fed=cash_at_fed,
            positions=positions
        )

    @staticmethod
    def get_breached_mf_global_style(as_of_date: date, total_float: Decimal = Decimal("500000000.00")) -> TreasuryPortfolio:
        """
        Non-Compliant / Stressed Case: Violates multiple CFTC 1.25 rules.
        60% in 5Y Notes (WAM breach), 35% in single GSE issuer (breaches 25% single GSE cap).
        """
        insts = {inst.id: inst for inst in get_standard_universe(as_of_date)}
        firm_ri = Decimal("5000000.00") # Tiny $5M RI buffer

        def make_pos(inst_id: str, pct: Decimal) -> Position:
            inst = insts[inst_id]
            alloc_usd = round_money(total_float * pct)
            par = round_money(alloc_usd / (inst.clean_price / Decimal("100.0")))
            return Position(instrument=inst, par_amount=par, book_cost=alloc_usd)

        # Use real 5-Year Treasury Note (91282CRA1, matures 07/31/2031) to demonstrate WAM breach
        positions = [
            make_pos("UST-NOTE-5Y", Decimal("0.60")),         # 60% in 5Y Notes (Causes WAM breach > 2.0 Yrs)
            make_pos("GSE-FNMA-3135G0Q22", Decimal("0.35")),  # 35% in single GSE (Breaches 25% single GSE cap)
            make_pos("UST-NOTE-2Y", Decimal("0.05")),         # 5%
        ]

        return TreasuryPortfolio(
            as_of_date=as_of_date,
            customer_segregated_liability=total_float,
            firm_residual_interest=firm_ri,
            cash_at_fed=firm_ri,
            positions=positions
        )

    @staticmethod
    def get_kalshi_us_treasuries_focused(as_of_date: date, total_float: Decimal = Decimal("11370355.00")) -> TreasuryPortfolio:
        """
        Kalshi-Specific CFTC 1.25 Portfolio:
        Ultra-liquid, pristine cash and short Treasury-bill allocation.
        """
        insts = {inst.id: inst for inst in get_standard_universe(as_of_date)}
        firm_ri = Decimal("4688126.00")

        def make_pos(inst_id: str, alloc_usd: Decimal) -> Position:
            inst = insts[inst_id]
            par = round_money(alloc_usd / (inst.clean_price / Decimal("100.0")))
            return Position(instrument=inst, par_amount=par, book_cost=alloc_usd)

        positions = [
            make_pos("REPO-ON-SOFR", round_money(total_float * Decimal("0.15"))),
            make_pos("UST-TBILL-4W", round_money(total_float * Decimal("0.15"))),
            make_pos("UST-TBILL-13W", round_money(total_float * Decimal("0.25"))),
            make_pos("UST-TBILL-26W", round_money(total_float * Decimal("0.10"))),
            make_pos("MMMF-BLK-TREASURY", round_money(total_float * Decimal("0.08"))),
            make_pos("MMMF-JPM-INST", round_money(total_float * Decimal("0.06"))),
            make_pos("GSE-FNMA-3135G0Q22", round_money(total_float * Decimal("0.05"))),
            make_pos("GSE-FFCB-3133EWXT2", round_money(total_float * Decimal("0.03"))),
        ]

        # 13% Cash at Fed + firm RI
        cash_at_fed = round_money(total_float * Decimal("0.13")) + firm_ri

        return TreasuryPortfolio(
            as_of_date=as_of_date,
            customer_segregated_liability=total_float,
            firm_residual_interest=firm_ri,
            cash_at_fed=cash_at_fed,
            positions=positions
        )
